config/routes.rb
Rails.application.routes.draw do

  root "products#index"
  resources :products do
    collection do
      get :soft_delete_index
    end
    member do
      get :recover
    end
  end

  resources :orders do
    member do
      post :add_item
      delete :remove_item
      post :place_order
      get :recover
    end
    collection do
      get :soft_delete_index
    end
    resources :order_items, only: [:create, :edit, :update, :destroy]
  end
  devise_for :users, sign_out_via: [:get]


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  acts_as_paranoid
  belongs_to :user
  has_many :order_items, dependent: :destroy

  accepts_nested_attributes_for :order_items

  enum :status, { pending: 0, completed: 1 }

  def add_product(product_id, quantity = 1)
    existing_item = order_items.find_by(product_id: product_id)
    if existing_item
      existing_item.increment!(:quantity, quantity)
    else
      order_items.create(product_id: product_id, quantity: quantity)
    end
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  acts_as_paranoid
  belongs_to :order
  belongs_to :product_including_deleted, class_name: "Product", foreign_key: 'product_id', with_deleted: true

  validates :quantity, numericality: { greater_than: 0 }

  def total_price
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    acts_as_paranoid
    has_many :order_items

    validates :name, :description, :price, presence: true
    validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy

  validates :username, presence: true
  after_create :default_role

  private

  def default_role
    self.add_role(:user) if self.roles.blank?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :find_or_create_pending_order

  def find_or_create_pending_order
    return unless current_user
    current_user.orders.find_or_create_by(status: "pending")
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order

  def edit
    @order_item = @order.order_items.find(params[:id])
  end

  def update
    @order_item = @order.order_items.find(params[:id])

    if @order_item.update(order_item_params)
      redirect_to @order, notice: "Order item updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_order
    @order = current_user.orders.find(params[:order_id])
  end

  def order_item_params
    params.require(:order_item).permit(:quantity)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = current_user.orders.all
  end

  def soft_delete_index
    @orders = current_user.orders.only_deleted.page(params[:page]).per(5)
  end

  def recover
    @order = current_user.orders.with_deleted.find(params[:id])
    @order.recover
    redirect_to @order, notice: "Order recoverd."
  end 
  
  def show
    @order = current_user.orders.with_deleted.find(params[:id])
    @order_items = @order.order_items.with_deleted
  end

  def new
    @order = current_user.orders.new
  end

  def create
    @order = current_user.orders.create!(status: :pending)
    redirect_to @order, notice: "Order created successfully."
  end

  def add_item
    @order = current_user.orders.find(params[:id])
    @order.add_product(params[:product_id])
    redirect_to @order, notice: "Product added to order."
  end

  def remove_item
    @order = current_user.orders.find(params[:id])
    @order_item = @order.order_items.find(params[:order_item_id])
    @order_item.destroy
    redirect_to @order, notice: "Order item removed."
  end

  def place_order
    @order = current_user.orders.find_by(id: params[:id])

    if @order.status == "pending"
      @order.update(status: "completed")
      redirect_to @order, notice: "order placed successfully."
    else
      redirect_to orders_path, alert: "Unable to place the order."
    end
  end

  def destroy
    @order = current_user.orders.with_deleted.find(params[:id])
    @order.destroy

    redirect_to orders_path, status: :see_other
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: %i[recover show edit update destroy]
  before_action :admin_access, only: %i[soft_delete_index recover new create edit update destroy]

  def index
    @products = Product.page(params[:page]).per(5)
  end

  def soft_delete_index
    @products = Product.only_deleted.page(params[:page]).per(5)
  end

  def recover
    @product.recover
    redirect_to @product, notice: "product recovered."
  end

  def show

  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)

    if @product.save 
      redirect_to @product, notice: "product created."
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: "product created."
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price)
  end

  def find_product
    @product = Product.with_deleted.find(params[:id])
  end

  def admin_access
    unless current_user.has_role?(:admin)
      redirect_to root_path, alert: "You are not authorized to perform this action."
    end
  end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Pawnstore" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav>
    <%= link_to "Home", root_path %>&nbsp&nbsp
    <% if user_signed_in? %>  
      <%= link_to "Log Out", destroy_user_session_path, method: :delete %>&nbsp&nbsp&nbsp&nbsp
      <br>
      <h1>Welcom <%= current_user.username %> To Our Site!</h1> 
      <% if current_user.has_role?(:admin) %>
        <%= link_to "Add New Product", new_product_path %>&nbsp&nbsp&nbsp
        <%= link_to "Removed Products", soft_delete_index_products_path %>
      <% else %>
        <%= link_to "Orders", orders_path %>
      <% end %>
    <% else %>
      <%= link_to "Log In", new_user_session_path %>&nbsp&nbsp 
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
  </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/order_items/edit.html.erb
<h1>Edit Order Item</h1>
<%= form_with model: [@order, @order_item], local: true do |f| %>
  <div>
    <%= f.label :quantity %>
    <%= f.number_field :quantity, min: 1 %>
  </div>

  <%= f.submit "Update Item" %>
<% end %>

app/views/orders/index.html.erb
<h1>Your Orders</h1>

<% if @orders.any? %>
  <table>
    <thead>
      <tr>
        <th>Order ID</th>
        <th>Status</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.id %></td>
          <td><%= order.status.capitalize %></td>
          <td>
            <%= link_to 'View Order', order_path(order) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>You don't have any orders yet.</p>
<% end %>
<br>
<%= link_to "Deleted Orders", soft_delete_index_orders_path %>&nbsp&nbsp&nbsp

<%= link_to 'Create New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>Add New Order</h1>
<%= form_with model: @order do |form| %>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/orders/show.html.erb
<h1>Order: <%= @order.id %></h1>
<p>Status: <%= @order.status.capitalize %></p>

<h2>Order Items</h2>
<% if @order.order_items.any? %>
  <table>
    <thead>
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Total Price</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @order_items.each do |item| %>
        <tr>
          <td><%= item.product.name.truncate(40, omission: '...') %></td>
          <td><%= item.quantity %></td>
          <td><%= item.total_price %></td>
          <td>
            <%= link_to "Edit", edit_order_order_item_path(@order, item) %>
          </td>
          <td>
            <%= button_to "Remove", remove_item_order_path(@order, order_item_id: item.id), method: :delete, data: { confirm: "Are you sure?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= button_to "Place Order", place_order_order_path(@order), method: :post %>
<% else %>
  <p> order is empty. </p>
<% end %>
<br>
<%= button_to "Delete", order_path(@order), method: :delete %>  
<h2>Add Item</h2>
<%= form_with url: add_item_order_path(@order), method: :post do |f| %>
  <%= f.label :product_id, "Select Product" %>
  <%= f.select :product_id, options_from_collection_for_select(Product.all, :id, :name) %>
  <%= f.label :quantity, "Quantity" %>
  <%= f.number_field :quantity, value: 1, min: 1 %>

  <%= f.submit "Add to Order" %>
<% end %>

app/views/orders/soft_delete_index.html.erb
<h1>Detleted Orders</h1>

<table>
  <thead>
    <tr>
      <th>Order ID</th>
      <th>Status</th>
      <th colspan="3">Actions </th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
        <tr>
        <td><%= order.id %></td>
        <td><%= order.status.capitalize %></td>
        <td><%= link_to 'View Order', order_path(order) %></td>
        <td><%= link_to "Recover", recover_order_path(order) %></td>
        <td><%= button_to "Delete", order_path(order), method: :delete %></td>
        </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
        <% product.errors.full_messages_for(:name).each do |message| %>
            <div><%= message %></div>
        <% end %> 
    </div>
    <br>
    <div>
        <%= form.label :description %>
        <%= form.text_area :description %>
        <% product.errors.full_messages_for(:description).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <br>
    <div>
        <%= form.label :price %>
        <%= form.number_field :price %>
        <% product.errors.full_messages_for(:price).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <br>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/products/edit.html.erb
<h1>Products</h1>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="2">Actions </th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name.truncate(40, omission: '...') %></td>
        <td><%= product.price %></td>
        <td><%= product.description.truncate(40, omission: '...') %></td>
        <td> <%= link_to "Show", product_path(product) %> </td>
        <td><%= button_to "Add to orders", add_item_order_path(find_or_create_pending_order, product_id: product.id), method: :post  %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div class="pagination">
  <%= paginate @products %>
</div>

app/views/products/new.html.erb
<h1>Products</h1>

<%= render "form", product: @product %>

app/views/products/show.html.erb
<h1>Product Details</h1>

<h2><strong>Name : </strong><%= @product.name %></h2>
<p><strong>Description : </strong><%= @product.description %></p>
<h2><strong>Price : </strong><%= @product.price %> Rs.</h2>

<% if current_user.has_role?(:admin) %>
    <%= button_to "Delete", product_path(@product), method: :delete %>
    <%= link_to "Edit", edit_product_path(@product) %>
<% else %>
    <%= button_to "Add to orders", add_item_order_path(find_or_create_pending_order, product_id: @product.id), method: :post  %> 
<% end %>

app/views/products/soft_delete_index.html.erb
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3">Actions </th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name.truncate(40, omission: '...') %></td>
        <td><%= product.price %></td>
        <td><%= product.description.truncate(40, omission: '...') %></td>
        <td> <%= link_to "Show", product_path(product) %> </td>
        <td><%= link_to "Recover", recover_product_path(product) %></td>
        <td><%= button_to "Delete", product_path(product), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div class="pagination">
  <%= paginate @products %>
</div>